#!/bin/bash
# Distributed by GNU public license
user=$USER
have_you_sudo=$(sudo -k || echo 'Error')
have_you_curl=$(curl --silent --output /dev/null example.com || echo 'Error')

# set language variable below with one of the country code from https://ftp.mozilla.org/pub/firefox/releases/latest/README.txt
# for example 'langueage=fr' to French Firefox version
language=en-US
clear

echo 'Install/Update Firefox script'
if [ ! -z "$have_you_sudo" ]; then
    echo 'Please give the credentials of superuser for install sudo in your system'
    su - root -c "apt install sudo -y && echo -e '$user    ALL=(ALL:ALL) ALL' >> /etc/sudoers"
    have_you_sudo=$(sudo || echo '')
    if [ -z "$have_you_sudo" ]; then 
        echo 'Done! now you have sudo in your system!'
    else
        echo 'A problem has ocurred! Please restart the script'
        return
    fi
fi

if [ ! -z "$have_you_curl" ]; then
    echo 'installing curl in your system'
    su - root -c "apt install curl -y"
    have_you_curl=$(curl --silent --output /dev/null example.com || echo 'Error')
    if [ -z "$have_you_curl" ]; then 
        echo 'Done! now you have curl in your system!'
    else
        echo 'A problem has ocurred! Please restart the script'
        return
    fi
fi

if [ ! -d /opt/firefox/releases ]; then
    sudo mkdir -p /opt/firefox/releases
fi

if [ ! -d /usr/lib/firefox-esr/ ]; then
    sudo mkdir -p /usr/lib/firefox-esr
fi

# The system core information (32bits or 64bits)
system=$(uname -a | awk '{print $9}')
#No error at the start
error_link=1

while [[ ! -z $error_link ]]; do
    if [ $system == 'x86_64' ] || [ $system == 'amd_64' ]; then
        link_firefox=$(curl -s "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=${language}" | awk '{ print $2 }' | cut -f2 -d'"')
        error_link=$(sudo wget -P /opt/firefox/releases -N $link_firefox || echo '\n\nLink not found! verify your internet conecction!... trying again\n\n');
    else
        link_firefox=$(curl -s "https://download.mozilla.org/?product=firefox-latest&os=linux&lang=${language}" | awk '{ print $2 }' | cut -f2 -d'"')
        error_link=$(sudo wget -P /opt/firefox/releases -N $link_firefox || echo '\n\nLink not found! verify your internet conecction!... trying again\n\n');
    fi
    echo -e $error_link
done

version=$(echo $link_firefox | cut -f7 -d'/')

# If is an install the flag will be empty if not will be 1 logic
install_or_update=$([ -f /opt/firefox/firefox ] && ls /opt/firefox/firefox || echo '')

# If the var is empty do the symbolic link and preserve the original link
if [[ -z $install_or_update ]]; then
    [ -f /usr/lib/firefox-esr/firefox-esr ] && sudo mv /usr/lib/firefox-esr/firefox-esr /usr/lib/firefox-esr/firefox-esr_orig
    [ -f /usr/lib/firefox-esr/firefox-esr ] && sudo ln -s /opt/firefox/firefox /usr/lib/firefox-esr/firefox-esr
fi

echo "The version of Firefox is $version"
error_unzip=$(sudo tar -f /opt/firefox/releases/firefox-$version.tar.bz2 --test-label || echo '\n\nERROR: The download has failed!...resuming download\n\n')

while [[ ! -z $error_unzip ]]; do
    echo -e $error_unzip
    wget -P /opt/firefox/releases/ -c $link_firefox
    error_unzip=$(sudo tar -f /opt/firefox/releases/firefox-$version.tar.bz2 --test-label || echo '\n\nERROR: The download has failed!...resuming download\n\n')
done

sudo tar xjf /opt/firefox/releases/firefox-$version.tar.bz2 -C /opt

if [[ -z $install_or_update ]]; then
    echo 'Firefox has been installed correctly!';
else
    echo 'Firefox has been updated correctly!';
fi

# Manage the versions
if [ ! -f '/opt/firefox/releases/actual_version' ]; then
    sudo su - root -c "echo $version > /opt/firefox/releases/actual_version"
else
    if [ -f '/opt/firefox/releases/old_version' ]; then
        actual_version=$(cat /opt/firefox/releases/actual_version)
        old_version=$(cat /opt/firefox/releases/old_version)
        if [ "$old_version" != "$actual_version" ]; then        
            sudo su - root -c "cat /opt/firefox/releases/actual_version > /opt/firefox/releases/old_version" 
            sudo su - root -c "echo $version > /opt/firefox/releases/actual_version"
            sudo rm -rf /opt/firefox/releases/firefox-$old_version.tar.bz2;
        fi
    else
        sudo su - root -c "cat /opt/firefox/releases/actual_version > /opt/firefox/releases/old_version" 
        sudo su - root -c "echo $version > /opt/firefox/releases/actual_version"
        sudo rm -rf /opt/firefox/releases/firefox-$old_version.tar.bz2;
    fi
fi
