#!/bin/bash
# Distributed by GNU public license
bash

have_you_sudo=$(sudo || echo '')
clear

if [[ -z $have_you_sudo ]]; then
    echo 'Please give the credentials of superuser for install sudo in your system'
    su - root -c "apt install sudo -y && echo '$USER    ALL=(ALL:ALL) ALL' > /etc/sudoers"
    have_you_sudo=$(sudo || echo '')
    if [[ -z $have_you_sudo ]]; then 
        echo 'Done! now you have sudo in your system!'
    else
        echo 'A problem has ocurred! Please restart the script'
        exit
    fi
fi

if [ ! -d /opt/firefox/script ]; then
    sudo mkdir /opt/firefox/script
fi

# This is the default folder to excute again this script
if [ ! -f '/opt/firefox/script/script_firefox' ]; then
    sudo cp -rf ./script_firefox /opt/firefox/script
    echo 'script copied! Now the script file is in /opt/firefox/script'
    sudo rm -rf ./script_firefox
fi

cd /opt/firefox/script

# The system core information (32bits or 64bits)
system=$(uname -a | awk '{print $9}')
#No error at the start
error_link=1

while [[ ! -z $error_link ]]; do
    if [ $system == 'x86_64' ] || [ $system == 'amd_64' ]; then
        link_firefox=$(curl -s "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" | awk '{ print $2 }' | cut -f2 -d'"')
        error_link=$(sudo wget -N $link_firefox || echo '\n\nLink not found! verify your internet conecction!... trying again\n\n');
    else
        link_firefox=$(curl -s "https://download.mozilla.org/?product=firefox-latest&os=linux&lang=en-US" | awk '{ print $2 }' | cut -f2 -d'"')
        error_link=$(sudo wget -N $link_firefox || echo '\n\nLink not found! verify your internet conecction!... trying again\n\n');
    fi
    echo -e $error_link
done

version=$(echo $link_firefox | cut -f7 -d'/')

# If is an install the flag will be empty if not will be 1 logic
install_or_update=$(ls /opt/firefox/firefox || echo '')

# If the var is empty do the simbolic link and preserve the original link
if [[ -z $install_or_update ]]; then
    sudo mv /usr/lib/firefox-esr/firefox-esr /usr/lib/firefox-esr/firefox-esr_orig
    sudo ln -s /opt/firefox/firefox/firefox /usr/lib/firefox-esr/firefox-esr
fi

error_unzip=$(sudo tar -f firefox-$version.tar.bz2 --test-label || echo '\n\nERROR: The download has failed!...resuming download\n\n')

while [[ ! -z $error_unzip ]]; do
    echo -e $error_unzip
    wget -c $link_firefox
    error_unzip=$(sudo tar -f firefox-$version.tar.bz2 --test-label || echo '\n\nERROR: The download has failed!...resuming download\n\n')
done

sudo tar xjf firefox-$version.tar.bz2 -C /opt/firefox  


if [[ -z $install_or_update ]]; then
    echo 'Firefox has been installed correctly!';
else
    echo 'Firefox has been installed correctly!';
fi

# Manage the versions
if [ ! -f 'actual_version' ]; then
    sudo su - root -c "echo $version > /opt/firefox/script/actual_version"
else
    if [ -f 'old_version' ]; then
        actual_version=$(cat actual_version)
        old_version=$(cat old_version)
        if [ "$old_version" != "$actual_version" ]; then        
            sudo su - root -c "cat /opt/firefox/script/actual_version > /opt/firefox/script/old_version" 
            sudo su - root -c "echo $version > /opt/firefox/script/actual_version"
            sudo rm -rf firefox-$old_version.tar.bz2;
        fi
    else
        sudo su - root -c "cat /opt/firefox/script/actual_version > /opt/firefox/script/old_version" 
        sudo su - root -c "echo $version > /opt/firefox/script/actual_version"
        sudo rm -rf firefox-$old_version.tar.bz2;
    fi
fi

exit
